package com.mulesoft.services;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import org.springframework.beans.factory.InitializingBean;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DerbyInitializeMappingTable implements InitializingBean {
    private static Logger logger = LoggerFactory.getLogger(DerbyInitializeMappingTable.class);
    
    public void afterPropertiesSet() throws Exception {
        String dbURL = "jdbc:derby:memory:muleEmbeddedDB;create=true";
        Connection conn = null;
        try {
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver").newInstance();
            conn = DriverManager.getConnection(dbURL);
            DatabaseMetaData md = conn.getMetaData();
            ResultSet rs = md.getTables(null, null, "%", null);
            logger.info("&&&& - DB Init - &&&&");
            int i=0;
            while (rs.next()){
                logger.info("there is next " + rs.getString(3));
                if(rs.getString(3).equalsIgnoreCase("DTMAPPING")) i=1; //set a marker that this table already exists
            }
            logger.info("&&&& - DB Init - &&&&");
            Statement stmt = conn.createStatement();
            if(i!=1){
            stmt.executeUpdate("CREATE TABLE DTMAPPING(ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0)  NOT NULL PRIMARY KEY," +
                    "SOURCESYSTEMID VARCHAR(255)," +
                    "TARGETSYSTEMID VARCHAR(255)," +
                    "TRANSLATEFIELDKEY VARCHAR(255)," +
                    "TRANSLATEFIELDSOURCEVALUE VARCHAR(255)," +
                    "TRANSLATEFIELDTARGETVALUE VARCHAR(255))");
            stmt.executeUpdate("INSERT INTO DTMAPPING(SOURCESYSTEMID, TARGETSYSTEMID, TRANSLATEFIELDKEY, TRANSLATEFIELDSOURCEVALUE, TRANSLATEFIELDTARGETVALUE) VALUES ('SalesForce', 'SAP','AccountNumber','123','876')");
            stmt.executeUpdate("INSERT INTO DTMAPPING(SOURCESYSTEMID, TARGETSYSTEMID, TRANSLATEFIELDKEY, TRANSLATEFIELDSOURCEVALUE, TRANSLATEFIELDTARGETVALUE) VALUES ('SalesForce', 'SAP','AccountNumber','456','865')");
            stmt.executeUpdate("INSERT INTO DTMAPPING(SOURCESYSTEMID, TARGETSYSTEMID, TRANSLATEFIELDKEY, TRANSLATEFIELDSOURCEVALUE, TRANSLATEFIELDTARGETVALUE) VALUES ('SalesForce', 'ORACLEDB','AccountNumber','789','765')");
            stmt.executeUpdate("INSERT INTO DTMAPPING(SOURCESYSTEMID, TARGETSYSTEMID, TRANSLATEFIELDKEY, TRANSLATEFIELDSOURCEVALUE, TRANSLATEFIELDTARGETVALUE) VALUES ('SAP', 'ORACLEDB','AccountNumber','821','745')");
            stmt.executeUpdate("INSERT INTO DTMAPPING(SOURCESYSTEMID, TARGETSYSTEMID, TRANSLATEFIELDKEY, TRANSLATEFIELDSOURCEVALUE, TRANSLATEFIELDTARGETVALUE) VALUES ('SAP', 'SalesForce','AccountNumber','892','145')");
            stmt.executeUpdate("INSERT INTO DTMAPPING(SOURCESYSTEMID, TARGETSYSTEMID, TRANSLATEFIELDKEY, TRANSLATEFIELDSOURCEVALUE, TRANSLATEFIELDTARGETVALUE) VALUES ('SAP', 'SalesForce','AccountNumber','882','245')");
//            ResultSet result = stmt.executeQuery("SELECT * FROM DTMAPPING");
//            while (result.next()) {
//                System.out.print("SOURCESYSTEMID: "+result.getString(1));
//                System.out.println("TRANSLATEFIELDTARGETVALUE: "+result.getString(5));
//            }
           }
            
        } 
        catch (java.sql.SQLException sqle) {
            sqle.printStackTrace();
            throw sqle;
        }
    }
    
//    public static void main(String[] args) throws Exception {
//    	DerbyInitializeMappingTable.afterPropertiesSet();
//    }
}